#!/bin/bash
#
# manage-svc.sh — Docker service lifecycle management
# Usage: manage-svc.sh [-i INVENTORY] [-h HOST] [-y] <service> <action>
#
# Actions: prepare | deploy | remove
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INVENTORY="${SCRIPT_DIR}/inventory/hosts.yml"
HOST=""
YES=false
TMPDIR="${SCRIPT_DIR}/tmp"

SUPPORTED_SERVICES=(
    redis
    dozzle
    cyberchef
    it-tools
    ladder
    freshrss
    homarr
    gitea
    arcane
    minio
    conduit
    obsidian
    traefik
)

SUPPORTED_ACTIONS=(prepare deploy remove)

declare -A STATE_MAP
STATE_MAP["prepare"]="prepare"
STATE_MAP["deploy"]="present"
STATE_MAP["remove"]="absent"

# ─── usage ──────────────────────────────────────────────────────────────────

usage() {
    cat <<EOF
Usage: $(basename "$0") [-i INVENTORY] [-h HOST] [-y] <service> <action>

Actions:
  prepare   Create directories and set ownership (one-time per service)
  deploy    Template configs + secrets, docker compose up
  remove    docker compose down, remove compose.yaml and secrets file
            Set DELETE_DATA=true to also remove Stacks data directory

Options:
  -i INVENTORY   Inventory file (default: inventory/hosts.yml)
  -h HOST        Target specific host (default: all hosts in <service>_svc group)
  -y             Skip confirmation prompts

Supported services: ${SUPPORTED_SERVICES[*]}

Examples:
  $(basename "$0") redis deploy
  $(basename "$0") -h truenas redis deploy
  DELETE_DATA=true $(basename "$0") redis remove
EOF
    exit 1
}

# ─── argument parsing ────────────────────────────────────────────────────────

while getopts "i:h:y" opt; do
    case $opt in
        i) INVENTORY="$OPTARG" ;;
        h) HOST="$OPTARG" ;;
        y) YES=true ;;
        *) usage ;;
    esac
done
shift $((OPTIND - 1))

[[ $# -lt 2 ]] && usage

SERVICE="$1"
ACTION="$2"

# ─── validation ──────────────────────────────────────────────────────────────

is_supported() {
    local needle="$1"; shift
    local -a haystack=("$@")
    for item in "${haystack[@]}"; do
        [[ "$item" == "$needle" ]] && return 0
    done
    return 1
}

if ! is_supported "$SERVICE" "${SUPPORTED_SERVICES[@]}"; then
    echo "ERROR: Unknown service '$SERVICE'"
    echo "Supported: ${SUPPORTED_SERVICES[*]}"
    exit 1
fi

if ! is_supported "$ACTION" "${SUPPORTED_ACTIONS[@]}"; then
    echo "ERROR: Unknown action '$ACTION'"
    echo "Supported: ${SUPPORTED_ACTIONS[*]}"
    exit 1
fi

STATE="${STATE_MAP[$ACTION]}"

# Inventory group names and Ansible variable names require underscores.
# SERVICE_VAR is used for the <service>_state variable in generated playbooks.
SERVICE_GROUP="${SERVICE//-/_}_svc"
SERVICE_VAR="${SERVICE//-/_}"

# ─── confirmation for remove ─────────────────────────────────────────────────

if [[ "$ACTION" == "remove" && "$YES" == false ]]; then
    echo "WARNING: This will stop and remove the $SERVICE service."
    if [[ "${DELETE_DATA:-false}" == "true" ]]; then
        echo "WARNING: DELETE_DATA=true — Stacks data will also be deleted!"
    fi
    read -r -p "Continue? [y/N] " confirm
    [[ "$confirm" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 0; }
fi

# ─── generate playbook ───────────────────────────────────────────────────────

mkdir -p "$TMPDIR"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
PLAYBOOK="${TMPDIR}/${SERVICE}-${ACTION}-${TIMESTAMP}.yml"

if [[ -n "$HOST" ]]; then
    HOSTS_TARGET="$HOST"
else
    HOSTS_TARGET="${SERVICE_GROUP}"
fi

cat > "$PLAYBOOK" <<EOF
---
# Generated by manage-svc.sh — $(date)
- name: Manage ${SERVICE} service (${ACTION})
  hosts: ${HOSTS_TARGET}
  vars:
    ${SERVICE_VAR}_state: ${STATE}
  roles:
    - role: ${SERVICE}
EOF

echo ""
echo "Service:  $SERVICE"
echo "Action:   $ACTION  (state: $STATE)"
echo "Hosts:    $HOSTS_TARGET"
echo "Inventory: $INVENTORY"
echo ""

# ─── run playbook ────────────────────────────────────────────────────────────

ANSIBLE_ARGS=("-i" "$INVENTORY" "$PLAYBOOK")

# Pass DELETE_DATA / DELETE_IMAGES through to Ansible if set
[[ "${DELETE_DATA:-}" == "true" ]]   && ANSIBLE_ARGS+=("-e" "delete_data_override=true")
[[ "${DELETE_IMAGES:-}" == "true" ]] && ANSIBLE_ARGS+=("-e" "delete_images_override=true")

if ansible-playbook "${ANSIBLE_ARGS[@]}"; then
    rm -f "$PLAYBOOK"
    echo ""
    echo "Done: $SERVICE $ACTION"
else
    echo ""
    echo "FAILED — playbook preserved at: $PLAYBOOK"
    exit 1
fi
