#!/bin/bash
#
# svc-exec.sh — Execute a service task (verify, configure, etc.)
# Usage: svc-exec.sh [-i INVENTORY] [-h HOST] <service> <task>
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INVENTORY="${SCRIPT_DIR}/inventory/hosts.yml"
HOST=""
TMPDIR="${SCRIPT_DIR}/tmp"

SUPPORTED_SERVICES=(
    redis
    dozzle
    cyberchef
    it-tools
    ladder
)

usage() {
    cat <<EOF
Usage: $(basename "$0") [-i INVENTORY] [-h HOST] <service> <task>

Tasks:
  verify   Run service health checks and functional tests

Options:
  -i INVENTORY   Inventory file (default: inventory/hosts.yml)
  -h HOST        Target specific host

Examples:
  $(basename "$0") redis verify
  $(basename "$0") -h truenas redis verify
EOF
    exit 1
}

while getopts "i:h:" opt; do
    case $opt in
        i) INVENTORY="$OPTARG" ;;
        h) HOST="$OPTARG" ;;
        *) usage ;;
    esac
done
shift $((OPTIND - 1))

[[ $# -lt 2 ]] && usage

SERVICE="$1"
TASK="$2"

TASK_FILE="${SCRIPT_DIR}/roles/${SERVICE}/tasks/${TASK}.yml"
if [[ ! -f "$TASK_FILE" ]]; then
    echo "ERROR: Task file not found: $TASK_FILE"
    exit 1
fi

mkdir -p "$TMPDIR"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
PLAYBOOK="${TMPDIR}/${SERVICE}-${TASK}-${TIMESTAMP}.yml"

# Inventory group names use underscores; service names may use hyphens.
SERVICE_GROUP="${SERVICE//-/_}_svc"

if [[ -n "$HOST" ]]; then
    HOSTS_TARGET="$HOST"
else
    HOSTS_TARGET="${SERVICE_GROUP}"
fi

cat > "$PLAYBOOK" <<EOF
---
# Generated by svc-exec.sh — $(date)
- name: Execute ${TASK} for ${SERVICE}
  hosts: ${HOSTS_TARGET}
  tasks:
    - name: Include ${TASK} tasks
      ansible.builtin.include_tasks:
        file: ${TASK_FILE}
EOF

echo "Service: $SERVICE  Task: $TASK  Hosts: $HOSTS_TARGET"
echo ""

if ansible-playbook -i "$INVENTORY" "$PLAYBOOK"; then
    rm -f "$PLAYBOOK"
else
    echo "FAILED — playbook preserved at: $PLAYBOOK"
    exit 1
fi
