#!/bin/bash
#
# svc-manage - Unified service management for solti-docker
#
# Replaces manage-svc.sh (state management) and svc-exec.sh (task execution)
# in a single script. The old scripts are preserved and unchanged.
#
# Usage: svc-manage [-i INVENTORY] [-h HOST] [-y] [-K] <service> <command> [options]
#
# State commands (prepare/deploy/remove) run the full role via main.yml.
# Task commands (verify/configure/<any>) run tasks_from inside the role.
#
# Hyphenated service names (arr-stack, it-tools) are converted to underscores
# for Ansible group names and variable names.
#
# Examples:
#   source ~/.secrets/LabProvision && source ~/.secrets/vpn.env
#   ./svc-manage.sh arr-stack prepare
#   ./svc-manage.sh arr-stack deploy
#   ./svc-manage.sh arr-stack verify
#   ./svc-manage.sh -h truenas arr-stack deploy
#   DELETE_DATA=true ./svc-manage.sh arr-stack remove

set -e

ANSIBLE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INVENTORY="${ANSIBLE_DIR}/inventory/hosts.yml"
TEMP_DIR="${ANSIBLE_DIR}/tmp"
HOST=""
YES_FLAG=false
EXPLICIT_INVENTORY=false
USE_SUDO=false

declare -A STATE_MAP
STATE_MAP["prepare"]="prepare"
STATE_MAP["deploy"]="present"
STATE_MAP["remove"]="absent"

SUPPORTED_STATES=("prepare" "deploy" "remove")

SUPPORTED_SERVICES=(
    "redis"
    "dozzle"
    "cyberchef"
    "it-tools"
    "ladder"
    "freshrss"
    "homarr"
    "gitea"
    "arcane"
    "minio"
    "conduit"
    "obsidian"
    "jellyfin"
    "traefik"
    "rustfs"
    "mongodb"
    "arr-stack"
    "vpn-torrent"
)

mkdir -p "${TEMP_DIR}"
chmod 700 "${TEMP_DIR}"

TEMP_PLAYBOOK=""
cleanup() {
    if [[ $? -eq 0 && -n "${TEMP_PLAYBOOK}" && -f "${TEMP_PLAYBOOK}" ]]; then
        rm -f "${TEMP_PLAYBOOK}"
    fi
}
trap cleanup EXIT INT TERM

usage() {
    cat << EOF
Usage: $(basename "$0") [-i INVENTORY] [-h HOST] [-y] [-K] <service> <command> [options]

Options:
  -i INVENTORY   Inventory file (default: inventory/hosts.yml)
  -h HOST        Target host (default: all hosts in <service>_svc group)
  -y             Skip safety prompts
  -K             Prompt for sudo (task commands only; state commands auto-detect)

State commands (run role main.yml):
  prepare        Create directories and set ownership (one-time per service)
  deploy         Template configs + secrets, docker compose up
  remove         docker compose down + cleanup (DELETE_DATA=true to also remove Stacks)

Task commands (run tasks_from inside role):
  verify         Health checks
  configure      Service-specific configuration
  <task>         Any task file in the role's tasks/ directory

Services:
$(printf '  %s\n' "${SUPPORTED_SERVICES[@]}")

Examples:
  $(basename "$0") redis deploy
  $(basename "$0") -h truenas arr-stack deploy
  $(basename "$0") arr-stack verify
  DELETE_DATA=true $(basename "$0") arr-stack remove
  $(basename "$0") redis deploy -e redis_image_tag=7.2-alpine
EOF
    exit 1
}

is_state() {
    local cmd="$1"
    for s in "${SUPPORTED_STATES[@]}"; do
        [[ "$s" == "$cmd" ]] && return 0
    done
    return 1
}

is_service_valid() {
    local svc="$1"
    for s in "${SUPPORTED_SERVICES[@]}"; do
        [[ "$s" == "$svc" ]] && return 0
    done
    return 1
}

# Hyphenated names (arr-stack, it-tools) → underscored for Ansible group/var names
service_var() { echo "${SERVICE//-/_}"; }
service_group() { echo "${SERVICE//-/_}_svc"; }

target_hosts() {
    [[ -n "$HOST" ]] && echo "$HOST" || service_group
}

prompt_user() {
    local command="$1"
    [[ "$YES_FLAG" == "true" ]] && return 0
    [[ "$command" == "verify" ]] && return 0

    local target; target=$(target_hosts)
    echo ""
    echo "WARNING: Remote target"
    echo "  Target:  ${target}"
    echo "  Service: ${SERVICE}"
    echo "  Command: ${command}"
    read -rp "Proceed? [y/N] " r
    [[ ! "$r" =~ ^[Yy] ]] && echo "Cancelled" && return 1
    return 0
}

probe_sudo() {
    local target="$1"
    echo "Probing sudo on ${target}..." >&2
    if ansible -i "${INVENTORY}" "${target}" -m shell -a "sudo -n true" &>/dev/null; then
        echo "NOPASSWD — no password needed" >&2
        echo "--become"
    else
        echo "Password required" >&2
        echo "--become --ask-become-pass"
    fi
}

generate_state_playbook() {
    local state="${STATE_MAP[$COMMAND]}"
    local hosts; hosts=$(target_hosts)
    local svar; svar=$(service_var)
    cat > "$TEMP_PLAYBOOK" << EOF
---
# Generated by svc-manage: ${SERVICE} ${COMMAND}
- name: ${COMMAND} ${SERVICE}
  hosts: ${hosts}
  vars:
    ${svar}_state: ${state}
  roles:
    - role: ${SERVICE}
EOF
}

generate_task_playbook() {
    local hosts; hosts=$(target_hosts)
    cat > "$TEMP_PLAYBOOK" << EOF
---
# Generated by svc-manage: ${SERVICE}/${COMMAND}
- name: Execute ${COMMAND} for ${SERVICE}
  hosts: ${hosts}
  gather_facts: false
  tasks:
    - name: "${SERVICE}/${COMMAND}"
      ansible.builtin.include_role:
        name: "${SERVICE}"
        tasks_from: "${COMMAND}"
EOF
}

# --- Parse options ---
while getopts "i:h:yK" opt; do
    case $opt in
        i) INVENTORY=$OPTARG; EXPLICIT_INVENTORY=true ;;
        h) HOST=$OPTARG ;;
        y) YES_FLAG=true ;;
        K) USE_SUDO=true ;;
        *) usage ;;
    esac
done
shift $((OPTIND - 1))

[[ $# -lt 2 ]] && { echo "Error: service and command required"; usage; }

SERVICE="$1"
COMMAND="$2"
shift 2
EXTRA_ARGS=("$@")

is_service_valid "$SERVICE" || { echo "Error: unknown service '${SERVICE}'"; usage; }
[[ -f "$INVENTORY" ]] || { echo "Error: inventory not found: ${INVENTORY}"; exit 1; }

TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
TEMP_PLAYBOOK="${TEMP_DIR}/${SERVICE}-${COMMAND}-${TIMESTAMP}.yml"

if is_state "$COMMAND"; then
    MODE="state"
    (umask 077 && generate_state_playbook)
else
    MODE="task"
    (umask 077 && generate_task_playbook)
fi

TARGET=$(target_hosts)
echo "Service:   ${SERVICE}"
echo "Command:   ${COMMAND}  (${MODE} mode)"
echo "Inventory: ${INVENTORY}"
echo "Target:    ${TARGET}"
echo ""
echo "--- playbook ---"
cat "$TEMP_PLAYBOOK"
echo "--- end ---"

prompt_user "$COMMAND" || exit 0

SUDO_FLAGS=""
if [[ "$MODE" == "state" ]]; then
    SUDO_FLAGS=$(probe_sudo "$TARGET")
elif [[ "$USE_SUDO" == "true" ]]; then
    SUDO_FLAGS=$(probe_sudo "$TARGET")
fi

START=$(date +%s)

echo "Running: ansible-playbook ${SUDO_FLAGS} -i ${INVENTORY} ${TEMP_PLAYBOOK} ${EXTRA_ARGS[*]}"
# shellcheck disable=SC2086
ansible-playbook ${SUDO_FLAGS} -i "${INVENTORY}" "${TEMP_PLAYBOOK}" "${EXTRA_ARGS[@]}"
EXIT_CODE=$?

DURATION=$(( $(date +%s) - START ))

if [[ $EXIT_CODE -eq 0 ]]; then
    echo ""
    echo "Success: ${SERVICE} ${COMMAND} completed (${DURATION}s)"
    exit 0
else
    echo ""
    echo "Failed: ${SERVICE} ${COMMAND} (exit ${EXIT_CODE})"
    echo "Playbook preserved for debugging: ${TEMP_PLAYBOOK}"
    exit $EXIT_CODE
fi
