---
traefik_state: present

traefik_version: "latest"
traefik_freeze: false
traefik_image: "traefik:{{ traefik_version }}"
traefik_host: "docker"
traefik_bind_ip: "127.0.0.1"
traefik_http_port: "80"
traefik_https_port: "443"

traefik_acme_email: "admin@example.com"
traefik_log_level: "WARN"

traefik_dashboard_allowlist: "192.168.0.0/16"

# Linode DNS API token for Let's Encrypt DNS challenge
traefik_linode_token: "{{ lookup('env', 'LINODE_TOKEN') }}"

# Networks created by traefik — other services reference these as external: true
traefik_networks:
  - name: "backend_storage"
    subnet: "172.20.42.0/24"
  - name: "backend_media"
    subnet: "172.20.43.0/24"
  - name: "traefik_public"
    subnet: ""

service_properties:
  name: "traefik"
  freeze: "{{ traefik_freeze }}"
  project_dir: "{{ install_root }}/Projects/traefik3"
  stack_dir: "{{ install_root }}/Stacks/traefik"
  secrets_file: "{{ install_root }}/Secrets/traefik.env"
  container_names:
    - "traefik"
  compose_networks: []
  dirs:
    - {path: "acme", mode: "0700"}
    - {path: "log",  mode: "0755"}
  delete_data: "{{ lookup('env', 'DELETE_DATA') | default(false) | bool }}"
  delete_images: "{{ lookup('env', 'DELETE_IMAGES') | default(false) | bool }}"
  images:
    - "{{ traefik_image }}"
